-- Autogenerated minimal init.lua: bootstrap lazy.nvim
-- Backups of previous init.lua were created if present.

local lazypath = vim.fn.stdpath('data') .. '/site/pack/lazy/opt/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ 'git', 'clone', '--filter=blob:none', 'https://github.com/folke/lazy.nvim.git', '--branch=stable', lazypath })
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = ' '           -- leader global = Space
vim.g.maplocalleader = '\\'     -- local leader = backslash

require('lazy').setup({
    spec = {
        -- Importar todos los plugins definidos en lua/plugins/*.lua
        { import = "plugins" },
    },
})

-- Optional: basic Neovim UI tweaks
vim.o.termguicolors = true
vim.o.background = 'dark'